[versions]
agp = "9.3.2"
kotlin = "2.4.10"
kotlinx-datetime = "0.8.0"
spotless = "8.10.0"
tyme4kt = "1.5.0"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
tyme4kt = { module = "cn.6tail:tyme4kt", version.ref = "tyme4kt" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
